services:
  - docker
language: go
go:
  - "1.14"

script:
  - 'if [ "${TRAVIS_BUILD_DIR}" != "${GOPATH}/src/github.com/DeviaVir/tfe-prometheus-exporter" ]; then ln -s "${TRAVIS_BUILD_DIR}" "${GOPATH}/src/github.com/DeviaVir/tfe-prometheus-exporter"; fi'
  - make vendor
  - make test
  - make
